from MultiTrain.classification.classification_models import MultiClassifier
from MultiTrain.classification.classification_models import subMultiClassifier
from MultiTrain.regression.regression_models import MultiRegressor
from MultiTrain.errors.errors import *
from MultiTrain.__version__ import __version__